// Invented names for seed athletes and users (CLAUDE.md: athlete names from the club's workbooks
// never enter the repository). Every athlete's first and last name is drawn from these lists,
// and test/world.test.ts checks that. Shell namesakes (Munn, Woodman, Lundberg, ...) are left
// out so a person never shares a name with a boat.

export const BOYS_FIRST_NAMES = [
  'Arlo',
  'Bennett',
  'Callum',
  'Dashiell',
  'Ellis',
  'Finnegan',
  'Gideon',
  'Harlan',
  'Idris',
  'Jasper',
  'Keaton',
  'Lachlan',
  'Matteo',
  'Nolan',
  'Oren',
  'Porter',
  'Quentin',
  'Rafferty',
  'Soren',
  'Tobias',
  'Ulises',
  'Vaughn',
  'Wesley',
  'Xander',
  'Yusuf',
  'Zane',
  'Anders',
  'Brooks',
  'Cyrus',
  'Dorian',
  'Emmett',
  'Fletcher',
  'Grady',
  'Hollis',
  'Jonah',
  'Kieran',
  'Leif',
  'Milo',
  'Nico',
  'Otis',
  'Rhys',
  'Silas',
  'Thatcher',
  'Wilder',
  'Ezra',
  'Rowan',
  'Beckett',
  'Caspian',
  'Desmond',
  'Everett',
] as const;

export const GIRLS_FIRST_NAMES = [
  'Adaline',
  'Briar',
  'Celeste',
  'Delphine',
  'Eloise',
  'Freya',
  'Greer',
  'Hazel',
  'Imogen',
  'Juniper',
  'Keira',
  'Linnea',
  'Marisol',
  'Nadia',
  'Odessa',
  'Paloma',
  'Quinn',
  'Rosalind',
  'Saoirse',
  'Tamsin',
  'Vivienne',
  'Wren',
  'Ximena',
  'Yara',
  'Zinnia',
  'Astrid',
  'Bianca',
  'Coralie',
  'Dahlia',
  'Esme',
  'Fiona',
  'Gemma',
  'Harper',
  'Isla',
  'Juno',
  'Kaia',
  'Lucia',
  'Maren',
  'Noor',
  'Opal',
  'Priya',
  'Romy',
  'Sienna',
  'Talia',
  'Elodie',
] as const;

export const MASTERS_MEN_FIRST_NAMES = [
  'Douglas',
  'Gregory',
  'Howard',
  'Kenneth',
  'Martin',
  'Russell',
  'Stuart',
  'Warren',
  'Bradley',
  'Curtis',
  'Duane',
  'Leland',
  'Neil',
  'Philip',
  'Raymond',
  'Victor',
] as const;

export const MASTERS_WOMEN_FIRST_NAMES = [
  'Beverly',
  'Colleen',
  'Denise',
  'Gail',
  'Heidi',
  'Janine',
  'Lorraine',
  'Noreen',
  'Patrice',
  'Rhonda',
  'Sheryl',
  'Tamara',
  'Yvonne',
  'Andrea',
  'Bridget',
  'Claudia',
  'Monique',
  'Renata',
] as const;

export const LAST_NAMES = [
  'Abernathy',
  'Ashby',
  'Bancroft',
  'Barlow',
  'Beaumont',
  'Blackwell',
  'Brannigan',
  'Calloway',
  'Carrington',
  'Chandler',
  'Coburn',
  'Corrigan',
  'Dalton',
  'Delacroix',
  'Draper',
  'Easton',
  'Ellsworth',
  'Falkner',
  'Farrow',
  'Fenwick',
  'Galloway',
  'Garrity',
  'Gillespie',
  'Halvorsen',
  'Hartwell',
  'Hawthorne',
  'Holloway',
  'Ingram',
  'Iverson',
  'Jaramillo',
  'Jessup',
  'Kavanagh',
  'Kessler',
  'Kincaid',
  'Lachance',
  'Lindqvist',
  'Lockhart',
  'Maddox',
  'Marchetti',
  'Merriweather',
  'Montague',
  'Nakamura',
  'Northcott',
  'Novak',
  'Oakley',
  'Okonkwo',
  'Ostrowski',
  'Pemberton',
  'Pennington',
  'Prescott',
  'Quimby',
  'Quintero',
  'Radcliffe',
  'Ramsey',
  'Rutledge',
  'Salazar',
  'Sandoval',
  'Sheffield',
  'Sinclair',
  'Solberg',
  'Stanton',
  'Talbot',
  'Thackeray',
  'Thornbury',
  'Underhill',
  'Upton',
  'Valdez',
  'Vance',
  'Wainwright',
  'Whitaker',
  'Winslow',
  'Yardley',
  'Yamamoto',
  'Zeller',
  'Albrecht',
  'Birch',
  'Cardenas',
  'Dunleavy',
  'Eriksen',
  'Fairbanks',
  'Grimaldi',
  'Hayashi',
  'Ibsen',
  'Jovanovic',
  'Kowalczyk',
  'Mistry',
  'Ortega',
  'Pacheco',
  'Rasmussen',
  'Sorensen',
  'Tanaka',
  'Ueda',
  'Varga',
  'Weatherby',
  'Xiong',
  'Ybarra',
  'Zapata',
  'Adeyemi',
  'Bergstrom',
  'Chowdhury',
  'Dimitrov',
  'Esposito',
  'Fujimoto',
  'Gallagher',
  'Haddad',
  'Iqbal',
  'Jankowski',
  'Kaur',
  'Lindgren',
  'Moreau',
  'Nilsson',
  'Obi',
  'Petrov',
  'Quigley',
  'Rinaldi',
  'Sato',
  'Toivonen',
  'Vukovic',
  'Whitfield',
  'Yilmaz',
  'Zielinski',
  'Arriola',
  'Brandt',
  'Delgado',
  'Enright',
  'Fontaine',
] as const;

/** Short forms some athletes go by (Athlete.preferredName). */
export const PREFERRED_NAMES: Readonly<Record<string, string>> = {
  Dashiell: 'Dash',
  Finnegan: 'Finn',
  Rafferty: 'Raff',
  Everett: 'Rett',
  Rosalind: 'Roz',
  Vivienne: 'Viv',
  Adaline: 'Addie',
  Gregory: 'Greg',
  Kenneth: 'Ken',
  Bradley: 'Brad',
  Philip: 'Phil',
};

export const ALL_FIRST_NAMES: ReadonlySet<string> = new Set([
  ...BOYS_FIRST_NAMES,
  ...GIRLS_FIRST_NAMES,
  ...MASTERS_MEN_FIRST_NAMES,
  ...MASTERS_WOMEN_FIRST_NAMES,
]);

export const ALL_LAST_NAMES: ReadonlySet<string> = new Set(LAST_NAMES);
