/// <reference path="../pb_data/types.d.ts" />
// Share links (PLAN.md §2, §8.1, §8.2; Phase 3).
//
// - Coaches and admins list, create, and revoke share links (revoke = set revoked_at). Only admins
//   delete them. Viewers see none.
// - The token is generated by the server (pb_hooks/share.pb.js); whatever a client sends is ignored.
// - created_by records who made the link (stamped by the hook).
// - The public, token-validated read and checklist routes live in pb_hooks/share.pb.js.

const EDIT = '@request.auth.role = "coach" || @request.auth.role = "admin"';
const ADMIN = '@request.auth.role = "admin"';

migrate(
  (app) => {
    const links = app.findCollectionByNameOrId('srt_share_links');
    links.listRule = EDIT;
    links.viewRule = EDIT;
    links.createRule = EDIT;
    links.updateRule = EDIT;
    links.deleteRule = ADMIN;
    links.fields.add(
      new Field({
        id: 'share_links__created_by',
        type: 'relation',
        name: 'created_by',
        collectionId: '_pb_users_auth_',
        maxSelect: 1,
        cascadeDelete: false,
      }),
    );
    links.addIndex('idx_share_links_regatta', false, 'regatta', '');
    app.save(links);
  },
  (app) => {
    const links = app.findCollectionByNameOrId('srt_share_links');
    links.listRule = ADMIN;
    links.viewRule = ADMIN;
    links.createRule = ADMIN;
    links.updateRule = ADMIN;
    links.deleteRule = ADMIN;
    links.removeIndex('idx_share_links_regatta');
    links.fields.removeByName('created_by');
    app.save(links);
  },
);
