// Generates packages/seed/src/generated/reference.ts from the CSVs in data/reference/, so the
// seed runs in Node and in the browser without file access. Run after changing a CSV:
//
//   pnpm --filter @regatta-ops/seed gen
//
// test/reference.test.ts fails when the generated file and the CSVs disagree.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { parseCsvObjects } from '@regatta-ops/domain';
import { REFERENCE_FILES } from '../src/reference-types';

const here = dirname(fileURLToPath(import.meta.url));
const referenceDir = resolve(here, '../../../data/reference');
const outFile = resolve(here, '../src/generated/reference.ts');

function readRows(file: string, columns: readonly string[]): Record<string, string>[] {
  const rows = parseCsvObjects(readFileSync(resolve(referenceDir, file), 'utf8'));
  const header = Object.keys(rows[0] ?? {});
  if (header.join(',') !== columns.join(',')) {
    throw new Error(
      `${file}: columns changed.\n  expected ${columns.join(',')}\n  found    ${header.join(',')}\n` +
        'Update src/reference-types.ts and the mapping code, then run gen again.',
    );
  }
  return rows;
}

const shells = readRows(REFERENCE_FILES.shells.file, REFERENCE_FILES.shells.columns);
const oarSets = readRows(REFERENCE_FILES.oarSets.file, REFERENCE_FILES.oarSets.columns);
const schedule = readRows(REFERENCE_FILES.schedule.file, REFERENCE_FILES.schedule.columns);

const source = `// Generated by packages/seed/scripts/gen-reference.ts from data/reference/*.csv. Do not edit.
// Run \`pnpm --filter @regatta-ops/seed gen\` after changing a CSV.

import type { OarSetRow, ScheduleRow, ShellRow } from '../reference-types';

/** data/reference/${REFERENCE_FILES.shells.file} */
export const SHELL_ROWS: readonly ShellRow[] = ${JSON.stringify(shells)};

/** data/reference/${REFERENCE_FILES.oarSets.file} */
export const OAR_SET_ROWS: readonly OarSetRow[] = ${JSON.stringify(oarSets)};

/** data/reference/${REFERENCE_FILES.schedule.file} */
export const SCHEDULE_ROWS: readonly ScheduleRow[] = ${JSON.stringify(schedule)};
`;

const config = (await prettier.resolveConfig(outFile)) ?? {};
writeFileSync(outFile, await prettier.format(source, { ...config, filepath: outFile }));
console.log(
  `Wrote ${outFile}: ${shells.length} shells, ${oarSets.length} oar sets, ${schedule.length} schedule rows.`,
);
